### ISSUE TITLE
Support Vite 3.x 

### ISSUE THREAD

**Issue by yfwz100** [yfwz100/vite-plugin-vue2-i18n#1]
Now Vite 3.x is out. The plugin should be updated to support that in order to eliminate the errors post by recent version of NPM.

**Comment by mpowell-atomic** [comment]
Hi. I made a PR for this. Hope this helps you (and me!):
https://github.com/yfwz100/vite-plugin-vue2-i18n/pull/2

**Comment by yfwz100** [comment]
Thanks for the PR :) I forget to make this change when I got back home. I'll release the version soon.

**Comment by pidgpowell** [comment]
Awesome! Thank you!

**Comment by yfwz100** [comment]
The version is released.

**Comment by pidgpowell** [comment]
Much appreciated!

**Comment by mpowell-atomic** [comment]
Much appreciated!
